//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.22 at 04:48:12 PM ICT 
//


package iso.std.iso._20022.tech.xsd.camt_060_001;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the iso.std.iso._20022.tech.xsd.camt_060_001 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Document_QNAME = new QName("urn:iso:std:iso:20022:tech:xsd:camt.060.001.07", "Document");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: iso.std.iso._20022.tech.xsd.camt_060_001
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Document }
     * 
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link SupplementaryDataEnvelope1 }
     * 
     */
    public SupplementaryDataEnvelope1 createSupplementaryDataEnvelope1() {
        return new SupplementaryDataEnvelope1();
    }

    /**
     * Create an instance of {@link SequenceRange1Choice }
     * 
     */
    public SequenceRange1Choice createSequenceRange1Choice() {
        return new SequenceRange1Choice();
    }

    /**
     * Create an instance of {@link GenericOrganisationIdentification3 }
     * 
     */
    public GenericOrganisationIdentification3 createGenericOrganisationIdentification3() {
        return new GenericOrganisationIdentification3();
    }

    /**
     * Create an instance of {@link TimePeriodDetails1 }
     * 
     */
    public TimePeriodDetails1 createTimePeriodDetails1() {
        return new TimePeriodDetails1();
    }

    /**
     * Create an instance of {@link GroupHeader117 }
     * 
     */
    public GroupHeader117 createGroupHeader117() {
        return new GroupHeader117();
    }

    /**
     * Create an instance of {@link FinancialInstitutionIdentification23 }
     * 
     */
    public FinancialInstitutionIdentification23 createFinancialInstitutionIdentification23() {
        return new FinancialInstitutionIdentification23();
    }

    /**
     * Create an instance of {@link ClearingSystemMemberIdentification2 }
     * 
     */
    public ClearingSystemMemberIdentification2 createClearingSystemMemberIdentification2() {
        return new ClearingSystemMemberIdentification2();
    }

    /**
     * Create an instance of {@link PersonIdentificationSchemeName1Choice }
     * 
     */
    public PersonIdentificationSchemeName1Choice createPersonIdentificationSchemeName1Choice() {
        return new PersonIdentificationSchemeName1Choice();
    }

    /**
     * Create an instance of {@link TransactionType2 }
     * 
     */
    public TransactionType2 createTransactionType2() {
        return new TransactionType2();
    }

    /**
     * Create an instance of {@link SequenceRange1 }
     * 
     */
    public SequenceRange1 createSequenceRange1() {
        return new SequenceRange1();
    }

    /**
     * Create an instance of {@link AccountIdentification4Choice }
     * 
     */
    public AccountIdentification4Choice createAccountIdentification4Choice() {
        return new AccountIdentification4Choice();
    }

    /**
     * Create an instance of {@link AddressType3Choice }
     * 
     */
    public AddressType3Choice createAddressType3Choice() {
        return new AddressType3Choice();
    }

    /**
     * Create an instance of {@link ActiveOrHistoricCurrencyAndAmount }
     * 
     */
    public ActiveOrHistoricCurrencyAndAmount createActiveOrHistoricCurrencyAndAmount() {
        return new ActiveOrHistoricCurrencyAndAmount();
    }

    /**
     * Create an instance of {@link Party50Choice }
     * 
     */
    public Party50Choice createParty50Choice() {
        return new Party50Choice();
    }

    /**
     * Create an instance of {@link ProxyAccountType1Choice }
     * 
     */
    public ProxyAccountType1Choice createProxyAccountType1Choice() {
        return new ProxyAccountType1Choice();
    }

    /**
     * Create an instance of {@link ClearingSystemIdentification2Choice }
     * 
     */
    public ClearingSystemIdentification2Choice createClearingSystemIdentification2Choice() {
        return new ClearingSystemIdentification2Choice();
    }

    /**
     * Create an instance of {@link CashAccountType2Choice }
     * 
     */
    public CashAccountType2Choice createCashAccountType2Choice() {
        return new CashAccountType2Choice();
    }

    /**
     * Create an instance of {@link OrganisationIdentificationSchemeName1Choice }
     * 
     */
    public OrganisationIdentificationSchemeName1Choice createOrganisationIdentificationSchemeName1Choice() {
        return new OrganisationIdentificationSchemeName1Choice();
    }

    /**
     * Create an instance of {@link GenericAccountIdentification1 }
     * 
     */
    public GenericAccountIdentification1 createGenericAccountIdentification1() {
        return new GenericAccountIdentification1();
    }

    /**
     * Create an instance of {@link SupplementaryData1 }
     * 
     */
    public SupplementaryData1 createSupplementaryData1() {
        return new SupplementaryData1();
    }

    /**
     * Create an instance of {@link BalanceSubType1Choice }
     * 
     */
    public BalanceSubType1Choice createBalanceSubType1Choice() {
        return new BalanceSubType1Choice();
    }

    /**
     * Create an instance of {@link OrganisationIdentification39 }
     * 
     */
    public OrganisationIdentification39 createOrganisationIdentification39() {
        return new OrganisationIdentification39();
    }

    /**
     * Create an instance of {@link GenericPersonIdentification2 }
     * 
     */
    public GenericPersonIdentification2 createGenericPersonIdentification2() {
        return new GenericPersonIdentification2();
    }

    /**
     * Create an instance of {@link BranchAndFinancialInstitutionIdentification8 }
     * 
     */
    public BranchAndFinancialInstitutionIdentification8 createBranchAndFinancialInstitutionIdentification8() {
        return new BranchAndFinancialInstitutionIdentification8();
    }

    /**
     * Create an instance of {@link PostalAddress27 }
     * 
     */
    public PostalAddress27 createPostalAddress27() {
        return new PostalAddress27();
    }

    /**
     * Create an instance of {@link AccountReportingRequestV07 }
     * 
     */
    public AccountReportingRequestV07 createAccountReportingRequestV07() {
        return new AccountReportingRequestV07();
    }

    /**
     * Create an instance of {@link ProxyAccountIdentification1 }
     * 
     */
    public ProxyAccountIdentification1 createProxyAccountIdentification1() {
        return new ProxyAccountIdentification1();
    }

    /**
     * Create an instance of {@link Contact13 }
     * 
     */
    public Contact13 createContact13() {
        return new Contact13();
    }

    /**
     * Create an instance of {@link EntryStatus1Choice }
     * 
     */
    public EntryStatus1Choice createEntryStatus1Choice() {
        return new EntryStatus1Choice();
    }

    /**
     * Create an instance of {@link BalanceType13 }
     * 
     */
    public BalanceType13 createBalanceType13() {
        return new BalanceType13();
    }

    /**
     * Create an instance of {@link DatePeriod3 }
     * 
     */
    public DatePeriod3 createDatePeriod3() {
        return new DatePeriod3();
    }

    /**
     * Create an instance of {@link GenericIdentification30 }
     * 
     */
    public GenericIdentification30 createGenericIdentification30() {
        return new GenericIdentification30();
    }

    /**
     * Create an instance of {@link Limit2 }
     * 
     */
    public Limit2 createLimit2() {
        return new Limit2();
    }

    /**
     * Create an instance of {@link BalanceType10Choice }
     * 
     */
    public BalanceType10Choice createBalanceType10Choice() {
        return new BalanceType10Choice();
    }

    /**
     * Create an instance of {@link PersonIdentification18 }
     * 
     */
    public PersonIdentification18 createPersonIdentification18() {
        return new PersonIdentification18();
    }

    /**
     * Create an instance of {@link AccountSchemeName1Choice }
     * 
     */
    public AccountSchemeName1Choice createAccountSchemeName1Choice() {
        return new AccountSchemeName1Choice();
    }

    /**
     * Create an instance of {@link DateAndPlaceOfBirth1 }
     * 
     */
    public DateAndPlaceOfBirth1 createDateAndPlaceOfBirth1() {
        return new DateAndPlaceOfBirth1();
    }

    /**
     * Create an instance of {@link ReportingPeriod5 }
     * 
     */
    public ReportingPeriod5 createReportingPeriod5() {
        return new ReportingPeriod5();
    }

    /**
     * Create an instance of {@link PartyIdentification272 }
     * 
     */
    public PartyIdentification272 createPartyIdentification272() {
        return new PartyIdentification272();
    }

    /**
     * Create an instance of {@link GenericFinancialIdentification1 }
     * 
     */
    public GenericFinancialIdentification1 createGenericFinancialIdentification1() {
        return new GenericFinancialIdentification1();
    }

    /**
     * Create an instance of {@link CashAccount40 }
     * 
     */
    public CashAccount40 createCashAccount40() {
        return new CashAccount40();
    }

    /**
     * Create an instance of {@link BranchData5 }
     * 
     */
    public BranchData5 createBranchData5() {
        return new BranchData5();
    }

    /**
     * Create an instance of {@link OtherContact1 }
     * 
     */
    public OtherContact1 createOtherContact1() {
        return new OtherContact1();
    }

    /**
     * Create an instance of {@link ReportingRequest7 }
     * 
     */
    public ReportingRequest7 createReportingRequest7() {
        return new ReportingRequest7();
    }

    /**
     * Create an instance of {@link Party52Choice }
     * 
     */
    public Party52Choice createParty52Choice() {
        return new Party52Choice();
    }

    /**
     * Create an instance of {@link FinancialIdentificationSchemeName1Choice }
     * 
     */
    public FinancialIdentificationSchemeName1Choice createFinancialIdentificationSchemeName1Choice() {
        return new FinancialIdentificationSchemeName1Choice();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Document }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:iso:std:iso:20022:tech:xsd:camt.060.001.07", name = "Document")
    public JAXBElement<Document> createDocument(Document value) {
        return new JAXBElement<Document>(_Document_QNAME, Document.class, null, value);
    }

}
