//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.22 at 02:58:12 PM ICT 
//


package iso.std.iso._20022.tech.xsd.camt_033_001;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the iso.std.iso._20022.tech.xsd.camt_033_001 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Document_QNAME = new QName("urn:iso:std:iso:20022:tech:xsd:camt.033.001.07", "Document");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: iso.std.iso._20022.tech.xsd.camt_033_001
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Document }
     * 
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link SupplementaryDataEnvelope1 }
     * 
     */
    public SupplementaryDataEnvelope1 createSupplementaryDataEnvelope1() {
        return new SupplementaryDataEnvelope1();
    }

    /**
     * Create an instance of {@link GenericOrganisationIdentification3 }
     * 
     */
    public GenericOrganisationIdentification3 createGenericOrganisationIdentification3() {
        return new GenericOrganisationIdentification3();
    }

    /**
     * Create an instance of {@link CaseAssignment6 }
     * 
     */
    public CaseAssignment6 createCaseAssignment6() {
        return new CaseAssignment6();
    }

    /**
     * Create an instance of {@link FinancialInstitutionIdentification23 }
     * 
     */
    public FinancialInstitutionIdentification23 createFinancialInstitutionIdentification23() {
        return new FinancialInstitutionIdentification23();
    }

    /**
     * Create an instance of {@link ClearingSystemMemberIdentification2 }
     * 
     */
    public ClearingSystemMemberIdentification2 createClearingSystemMemberIdentification2() {
        return new ClearingSystemMemberIdentification2();
    }

    /**
     * Create an instance of {@link PersonIdentificationSchemeName1Choice }
     * 
     */
    public PersonIdentificationSchemeName1Choice createPersonIdentificationSchemeName1Choice() {
        return new PersonIdentificationSchemeName1Choice();
    }

    /**
     * Create an instance of {@link AddressType3Choice }
     * 
     */
    public AddressType3Choice createAddressType3Choice() {
        return new AddressType3Choice();
    }

    /**
     * Create an instance of {@link Party50Choice }
     * 
     */
    public Party50Choice createParty50Choice() {
        return new Party50Choice();
    }

    /**
     * Create an instance of {@link ClearingSystemIdentification2Choice }
     * 
     */
    public ClearingSystemIdentification2Choice createClearingSystemIdentification2Choice() {
        return new ClearingSystemIdentification2Choice();
    }

    /**
     * Create an instance of {@link OrganisationIdentificationSchemeName1Choice }
     * 
     */
    public OrganisationIdentificationSchemeName1Choice createOrganisationIdentificationSchemeName1Choice() {
        return new OrganisationIdentificationSchemeName1Choice();
    }

    /**
     * Create an instance of {@link SupplementaryData1 }
     * 
     */
    public SupplementaryData1 createSupplementaryData1() {
        return new SupplementaryData1();
    }

    /**
     * Create an instance of {@link Case6 }
     * 
     */
    public Case6 createCase6() {
        return new Case6();
    }

    /**
     * Create an instance of {@link OrganisationIdentification39 }
     * 
     */
    public OrganisationIdentification39 createOrganisationIdentification39() {
        return new OrganisationIdentification39();
    }

    /**
     * Create an instance of {@link GenericPersonIdentification2 }
     * 
     */
    public GenericPersonIdentification2 createGenericPersonIdentification2() {
        return new GenericPersonIdentification2();
    }

    /**
     * Create an instance of {@link BranchAndFinancialInstitutionIdentification8 }
     * 
     */
    public BranchAndFinancialInstitutionIdentification8 createBranchAndFinancialInstitutionIdentification8() {
        return new BranchAndFinancialInstitutionIdentification8();
    }

    /**
     * Create an instance of {@link PostalAddress27 }
     * 
     */
    public PostalAddress27 createPostalAddress27() {
        return new PostalAddress27();
    }

    /**
     * Create an instance of {@link RequestForDuplicateV07 }
     * 
     */
    public RequestForDuplicateV07 createRequestForDuplicateV07() {
        return new RequestForDuplicateV07();
    }

    /**
     * Create an instance of {@link Contact13 }
     * 
     */
    public Contact13 createContact13() {
        return new Contact13();
    }

    /**
     * Create an instance of {@link GenericIdentification30 }
     * 
     */
    public GenericIdentification30 createGenericIdentification30() {
        return new GenericIdentification30();
    }

    /**
     * Create an instance of {@link PersonIdentification18 }
     * 
     */
    public PersonIdentification18 createPersonIdentification18() {
        return new PersonIdentification18();
    }

    /**
     * Create an instance of {@link DateAndPlaceOfBirth1 }
     * 
     */
    public DateAndPlaceOfBirth1 createDateAndPlaceOfBirth1() {
        return new DateAndPlaceOfBirth1();
    }

    /**
     * Create an instance of {@link PartyIdentification272 }
     * 
     */
    public PartyIdentification272 createPartyIdentification272() {
        return new PartyIdentification272();
    }

    /**
     * Create an instance of {@link GenericFinancialIdentification1 }
     * 
     */
    public GenericFinancialIdentification1 createGenericFinancialIdentification1() {
        return new GenericFinancialIdentification1();
    }

    /**
     * Create an instance of {@link BranchData5 }
     * 
     */
    public BranchData5 createBranchData5() {
        return new BranchData5();
    }

    /**
     * Create an instance of {@link OtherContact1 }
     * 
     */
    public OtherContact1 createOtherContact1() {
        return new OtherContact1();
    }

    /**
     * Create an instance of {@link Party52Choice }
     * 
     */
    public Party52Choice createParty52Choice() {
        return new Party52Choice();
    }

    /**
     * Create an instance of {@link FinancialIdentificationSchemeName1Choice }
     * 
     */
    public FinancialIdentificationSchemeName1Choice createFinancialIdentificationSchemeName1Choice() {
        return new FinancialIdentificationSchemeName1Choice();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Document }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:iso:std:iso:20022:tech:xsd:camt.033.001.07", name = "Document")
    public JAXBElement<Document> createDocument(Document value) {
        return new JAXBElement<Document>(_Document_QNAME, Document.class, null, value);
    }

}
