//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.22 at 03:16:04 PM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:iso:std:iso:20022:tech:xsd:pacs.010.001.06", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package iso.std.iso._20022.tech.xsd.pacs_010_001;
